In [1]:
import sys
sys.path.insert(1, '../scripts/')
from preprocess import preprocess

First, format the project input files and generate the environment

In [2]:
# # downloaded project inputs
# input_data_path, build_files_path = preprocess.unpack_files(data_files = '/data2/hratch/human_me/data.zip', 
#                                         build_files = '/data2/hratch/human_me/build_files.zip', 
#                                         data_out = '/data2/hratch/human_me/raw')
# preprocess.create_environment(input_data_path, build_files_path, root_path = '/home/hratch/Projects/human_me/',
#                               processed_data_path = '/data2/hratch/human_me/processed/', 
#                               n_cores = 20)

In [3]:
from preprocess import correct_inputs

full model

In [4]:
# correct_inputs.correct_model(model_file = '/data2/hratch/human_me/input_files/recon2_2.xml', 
#                  psim_file = '/data2/hratch/human_me/input_files/psim_recon2_2.csv')

# correct_inputs.correct_psim(psim_file = '/data2/hratch/human_me/input_files/psim_recon2_2.csv')
# # # optional - only if you want to express non-machinery proteins
# # correct_inputs.check_non_machinery(nonmachinery_file = '/data2/hratch/human_me/input_files/non_machinery.txt')

# from expression import build_me_model
# me_model, builder = build_me_model.build_me(minimal_proteome = False, compress_mrna = False)

# import pickle
# lp_path = '/data2/hratch/human_me/test_lp/'
# with open(lp_path + 'me_model.pickle', 'wb') as handle:
#     pickle.dump(me_model, handle)

toy model

In [5]:
# correct_inputs.correct_model(model_file = '/data2/hratch/human_me/input_files/toy_model.xml', 
#                  psim_file = '/data2/hratch/human_me/input_files/psim_recon2_2.csv')

# correct_inputs.correct_psim(psim_file = '/data2/hratch/human_me/input_files/psim_recon2_2.csv')

# from expression import build_me_model
# toy_me_model, builder = build_me_model.build_me(minimal_proteome = True, compress_mrna = False, 
#                                                 model_id = 'toy_me_model')

# import pickle
# lp_path = '/data2/hratch/human_me/test_lp/'
# with open(lp_path + 'toy_me_model.pickle', 'wb') as handle:
#     pickle.dump(toy_me_model, handle)

# Check

In [6]:
# from expression import build_me_model
# toy_me_model, builder = build_me_model.build_me(minimal_proteome = True, compress_mrna = False, 
#                                                 unmodeled_protein_frac = None,
#                                                 model_id = 'toy_me_model')
# jabba = True
# if jabba:
#     for r in toy_me_model.reactions:
#         if ('EX_' in r.id and r.compartments == {'b'} and r.bounds == (float('-inf'), float('inf'))):
#             r._lower_bound = -1000
#             r._upper_bound = 1000
            
# sln, stat, _ = toy_me_model.solve_lp(mu_val = 1e-9)

In [7]:
# import pandas as pd
# res = pd.DataFrame(data = {'reaction_fluxes': sln[:len(toy_me_model.reactions)]})
# res.index = [r.id for r in toy_me_model.reactions]

In [8]:
# res.loc[[i for i in res.index if 'biomass' in i],:]

In [9]:
# import pickle
# lp_path = '/data2/hratch/human_me/test_lp/'
# with open(lp_path + 'working_version_' + str(0) + '.pickle', 'wb') as handle:
#     pickle.dump(toy_me_model, handle)

# S = toy_me_model.create_stoichiometric_matrix(mu_val = 1, inplace = False, array_type = 'pandas')
# fn = '/data2/hratch/human_me/test_lp/S_matrix.h5'
# S.to_hdf(fn, key = str(0), mode = 'w')

In [10]:
from expression import build_me_model
toy_me_model, builder = build_me_model.build_me(minimal_proteome = True, compress_mrna = False, 
                                                unmodeled_protein_frac = None,
                                                model_id = 'toy_me_model')

ERROR:cobra.io.sbml:No objective coefficients in model. Unclear what should be optimized

Generate ubiquitin reactions for proteasomal degradation
Generate ribosome

../scripts/expression/gene_information.py:113 UserWarning: HGNC:10368: The letter X is in the protein sequence. Replacing with a random amino acid
  1%|          | 7/591 [00:00<00:09, 64.19it/s]

Generate protein expression reactions for metabolic enzymes and non-machinery

100%|██████████| 591/591 [00:10<00:00, 56.30it/s]

Generate protein expression reactions for expression module enzymes, this step may take a few minutes

100%|██████████| 510/510 [00:10<00:00, 48.10it/s]
  1%|          | 4/512 [00:00<00:13, 38.99it/s]

No. iterations for new expression machinery: 1

100%|██████████| 512/512 [00:12<00:00, 41.25it/s]
 19%|█▉        | 177/938 [00:00<00:00, 1769.22it/s]

Get metabolic module complex information

100%|██████████| 938/938 [00:00<00:00, 1070.54it/s]
  1%|          | 117/12843 [00:00<00:10, 1165.43it/s]

Get expression module complex information

100%|██████████| 12843/12843 [01:14<00:00, 171.43it/s]

Assign unique complex ids for unique machinery-compartment sets across all reactions

 14%|█▎        | 166/1219 [00:00<00:00, 1652.82it/s]

Calculate enzyme k_effs

100%|██████████| 1219/1219 [00:00<00:00, 1699.39it/s]
 11%|█         | 52/489 [00:00<00:00, 518.28it/s]

A total of 1897 reactions were dropped when forming a minimal proteome
Add machinery to metabolic module reactions

100%|██████████| 489/489 [00:00<00:00, 564.47it/s]
  0%|          | 48/10649 [00:00<00:22, 473.31it/s]

Add machinery to expression module reactions

100%|██████████| 10649/10649 [00:22<00:00, 463.88it/s]

Add biomass component to reactions
Generate ME-Model

 22%|██▏       | 2787/12494 [00:00<00:00, 27779.88it/s]

Check reaction mass balances

100%|██████████| 12494/12494 [00:01<00:00, 9342.09it/s]

Check correct coupling of metabolic machinery
Time to build: 4.071490255991618 minutes

In [11]:
toy_me_model.initialize_solver()
mu_max, res = toy_me_model.maximize_growth(min_mu = 0, max_mu = 1000, mu_accuracy = 600)

Trying mu: 0
The problem has an optimal solution at mu = 0 (hrs)
The problem is infeasible at mu = 1000 (hrs)
Trying mu: 500.0
The problem is infeasible at mu = 500.0 (hrs)
completed in 0.02 hours and 3 iterations

# Check dummy

In [10]:
from expression import build_me_model
from uniform_processes import biomass
from utils import parameters as params
import copy
import pandas as pd
import numpy as np
from tqdm import tqdm
import multiprocessing
from core.reaction import ME_Reaction


def get_mod(frac):
    store = dict()
    m_id = 'dummy_{}'.format(frac) if frac is not None else 'no_dummy'

    model, builder = build_me_model.build_me(non_machinery = [], minimal_proteome = True, 
                   compress_mrna = False, unmodeled_protein_frac = frac, model_id = m_id)
    
    bad_rxn = list()
    for r in params.human_model.reactions:
        if len(r.genes) == 0:
            for r_ in model.reactions: 
                if isinstance(r_, ME_Reaction):
                    if (r_.id == r.id) or (r_.cobra_id == r.id):
                        if len({k for k,v in r_.coupled_metabolites.items() if 'HGNC:DUMMY' not in k.id}) > 0:
                            bad_rxn.append(r_.id)
                        break
    if len(bad_rxn) > 0
    

    models = [model]
    if frac is not None:
        sink_model = copy.deepcopy(model)
        sink_model.id = 'dummy_sink_{}'.format(frac)
        sink_model.add_boundary(sink_model.metabolites.get_by_id('HGNC:10419_folded_protein_c'), type = 'sink')
        models.append(sink_model)

    for model in models:
        store[model.id] = {'model': model, 'builder': builder}

        print('Solve ' + m_id)
        sln, stat, _ = store[model.id]['model'].solve_lp(mu_val = 1e-9)
        ir = store[model.id]['model'].infeasible_reactions(1e-9, sln, stat)

        store[model.id]['sln'] = sln
        store[model.id]['stat'] = stat
        store[model.id]['infeasible_reactions'] = ir

    return store

def get_mods(fracs, n_cores = 3):
    pool = multiprocessing.Pool(processes = n_cores)
    stores = pool.map(get_mod,fracs)
    pool.close()
    return stores

ERROR:cobra.io.sbml:No objective coefficients in model. Unclear what should be optimized

In [38]:
stores = get_mods(fracs = [None, 0.001, params.unmodeled_protein_frac])

res = dict()
for store in stores:
    for k,v in store.items():
        res[k] = v
print(list(res.keys()))

['no_dummy', 'dummy_0.001', 'dummy_sink_0.001', 'dummy_0.879584658137385', 'dummy_sink_0.879584658137385']

In [71]:
tol = np.max([abs(v) for v in res['no_dummy']['infeasible_reactions'].values()])

r_ids = []
for k_ in res:
    r_ids += [k for k,v in res[k_]['infeasible_reactions'].items() if abs(v) > tol]

r_ids = pd.Series([biomass.pb_reaction.id] + [r.id for r in biomass.biomass_reactions]  + r_ids).unique().tolist()
res_df = pd.DataFrame(columns = res.keys(), index = r_ids)    

for k in res.keys():
    for r_id in r_ids:
        try:
            res_df.loc[r_id, k] = res[k]['sln'][res[k]['model'].reactions.index(r_id)]
        except:
            res_df.loc[r_id, k] = float('nan')

fail = res_df[abs(res_df['dummy_0.879584658137385'] - res_df['dummy_sink_0.879584658137385']) > tol]

In [125]:
model = res['no_dummy']['model']

In [221]:
self = res['no_dummy']['model']
self.m_model = params.human_model.copy()
mismatch = check_coupling(self)

Check correct coupling of metabolic machinery

In [222]:
mismatch

{}

In [220]:
len(res['no_dummy']['model'].reactions)

12495

In [210]:
len(self.reactions)

12792

In [195]:
r = self.reactions.get_by_id('ADNK1m')
r_ = self.m_model.reactions.get_by_id('ADNK1m')
machinery = [m for m,v in r.coupled_metabolites.items() if v == 'catalysis']
machinery = machinery[0]

In [200]:
mach = machinery.decompose_complex() if isinstance(machinery, Complex) else [machinery]

In [202]:
mach_me = [m.id.split('_')[0] for m in mach]
mach_m = [g.id for g in list(r_.genes)]

In [203]:
mach_me

['HGNC:DUMMY']

In [204]:
mach_m

[]

In [199]:
((len(r_.genes) == 0) and (machinery.id != 'HGNC:DUMMY_folded_protein_c')) or ((len(r_.genes) > 0) and (machinery.id == 'HGNC:DUMMY_folded_protein_c'))

False

In [185]:
mismatch

{'ADNK1m': 'HGNC:DUMMY_folded_protein_c',
 'ARTCOAL3': 'HGNC:DUMMY_folded_protein_c',
 'R_group_phosphotase_3': 'HGNC:DUMMY_folded_protein_c',
 'ARTPLM3_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'ARTPLM3_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BDMT_U': 'HGNC:DUMMY_folded_protein_c',
 'DDPGAm_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DDPGAm_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DOLASNT_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLDPP_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLPGT1_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLPGT2_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLPGT3_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLPMT_U': 'HGNC:DUMMY_folded_protein_c',
 'DOLPMT1_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLPMT2_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLPMT3_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DOLPMT4_Uer': 'HGNC:DUMMY_folded_protein_c',
 'DSAT': 'HGNC:DUMMY_folded_protein_c',
 'ENGASEly': 'HGNC:DUMMY_folded_protein_c',
 'G12MT1_U': 'HGNC:DUMMY_folded_protein_c',
 'G12MT2_U': 'HGNC:DUMMY_folded_protein_c',
 'G13MT_U': 'HGNC:DUMMY_folded_protein_c',
 'G16MT_U': 'HGNC:DUMMY_folded_protein_c',
 'GLCNACPT_U': 'HGNC:DUMMY_folded_protein_c',
 'GLCNACT_U': 'HGNC:DUMMY_folded_protein_c',
 'NICRNS': 'HGNC:DUMMY_folded_protein_c',
 'PRO1xm': 'HGNC:DUMMY_folded_protein_c',
 'TRIOK': 'HGNC:DUMMY_folded_protein_c',
 'UDPDOLPT_U': 'HGNC:DUMMY_folded_protein_c',
 'r0062': 'HGNC:DUMMY_folded_protein_c',
 'r0179': 'HGNC:DUMMY_folded_protein_c',
 'r0456': 'HGNC:DUMMY_folded_protein_c',
 'r0466': 'HGNC:DUMMY_folded_protein_c',
 'r0480_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r0480_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r0584_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r0584_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r0788_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r0788_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r0789_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r0789_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r1146_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'r1146_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE1447M_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE1447M_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE2659R_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE2659R_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE2675C': 'HGNC:DUMMY_folded_protein_c',
 'RE3237C_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE3237C_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE3245C_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE3245C_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE3347C_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RE3347C_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'FAOXC5C5OHm': 'HGNC:DUMMY_folded_protein_c',
 'ADNK3': 'HGNC:DUMMY_folded_protein_c',
 '10FTHF6GLUtl': 'HGNC:DUMMY_folded_protein_c',
 '10FTHFtl_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 '10FTHFtl_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 '4ABUTtm_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 '4ABUTtm_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 '4MOPt2im': 'HGNC:DUMMY_folded_protein_c',
 'ACALDt_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'ACALDt_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'ACGAMtly': 'HGNC:DUMMY_folded_protein_c',
 'ARTFR12': 'HGNC:DUMMY_folded_protein_c',
 'Asn_X_Ser_Thrtr_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'Asn_X_Ser_Thrtr_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BHBt_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BHBt_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BHBtm_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BHBtm_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BILGLCURtr_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BILGLCURtr_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BILIRUBtr_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'BILIRUBtr_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'C226CRNt': 'HGNC:DUMMY_folded_protein_c',
 'CO2t_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'CO2t_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'CO2ter_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'CO2ter_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'CRVNCtr_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'CRVNCtr_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DATPtn_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DATPtn_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DCTPtn_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DCTPtn_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DGTPtn_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DGTPtn_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DOLGLCP_Lter': 'HGNC:DUMMY_folded_protein_c',
 'DOLMANP_Lter': 'HGNC:DUMMY_folded_protein_c',
 'DOLP_Uter': 'HGNC:DUMMY_folded_protein_c',
 'DTTPtn_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'DTTPtn_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'FADH2tru': 'HGNC:DUMMY_folded_protein_c',
 'FADtru': 'HGNC:DUMMY_folded_protein_c',
 'FORtr_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'FORtr_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GALtly': 'HGNC:DUMMY_folded_protein_c',
 'GDPtg_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GDPtg_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GLCter_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GLCter_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GLUt7l': 'HGNC:DUMMY_folded_protein_c',
 'GLXtm_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GLXtm_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GMPtg_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'GMPtg_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2O2t_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2O2t_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2O2tm': 'HGNC:DUMMY_folded_protein_c',
 'H2Oter_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2Oter_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2Otg_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2Otg_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2Otly_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'H2Otly_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'HMGCOAtm_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'HMGCOAtm_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'Htg_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'Htg_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'Htr_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'Htr_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'M4MPDOL_Uter': 'HGNC:DUMMY_folded_protein_c',
 'M7MASNBterg': 'HGNC:DUMMY_folded_protein_c',
 'M8MASNterg': 'HGNC:DUMMY_folded_protein_c',
 'MANter': 'HGNC:DUMMY_folded_protein_c',
 'MANtg': 'HGNC:DUMMY_folded_protein_c',
 'MANtly': 'HGNC:DUMMY_folded_protein_c',
 'NADHtru': 'HGNC:DUMMY_folded_protein_c',
 'NADPHtru': 'HGNC:DUMMY_folded_protein_c',
 'NADPtru': 'HGNC:DUMMY_folded_protein_c',
 'NADtru': 'HGNC:DUMMY_folded_protein_c',
 'O2St_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2St_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2Stm_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2Stm_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2t_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2t_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2ter_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2ter_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2tm_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'O2tm_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PCHOL_HSter_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PCHOL_HSter_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PE_HSter_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PE_HSter_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PEt_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PEt_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PGLYCt_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PGLYCt_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PItg': 'HGNC:DUMMY_folded_protein_c',
 'PPItr_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PPItr_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PSt3_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'PSt3_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RETNGLCt2': 'HGNC:DUMMY_folded_protein_c',
 'RETNGLCt2r': 'HGNC:DUMMY_folded_protein_c',
 'RETNt_F': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RETNt_R': 'FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m',
 'RETNtr': 'HGNC:DUMMY_folded_protein_c',
 'RETNtr2': 'HGNC:DUMMY_folded_protein_c',
 'S2L2FN2M2MASNt': 'HGNC:DUMMY_folded_protein_c',
 'S2L2N2M2MASNtly': 'HGNC:DUMMY_folded_protein_c',

In [159]:
self.reactions.get_by_id('ADNK1m')

In [160]:
self

In [163]:
'ADNK1m' in [r.id for r in self.m_model.boundary]

False

In [157]:
unchecked

['ADNK1m',
 'ARTCOAL3',
 'R_group_phosphotase_3',
 'ARTPLM3',
 'BDMT_U',
 'DDPGAm',
 'DOLASNT_Uer',
 'DOLDPP_Uer',
 'DOLPGT1_Uer',
 'DOLPGT2_Uer',
 'DOLPGT3_Uer',
 'DOLPMT_U',
 'DOLPMT1_Uer',
 'DOLPMT2_Uer',
 'DOLPMT3_Uer',
 'DOLPMT4_Uer',
 'DSAT',
 'ENGASEly',
 'G12MT1_U',
 'G12MT2_U',
 'G13MT_U',
 'G16MT_U',
 'GLCNACPT_U',
 'GLCNACT_U',
 'NICRNS',
 'PRO1xm',
 'TRIOK',
 'UDPDOLPT_U',
 'r0062',
 'r0179',
 'r0456',
 'r0466',
 'r0480',
 'r0584',
 'r0788',
 'r0789',
 'r1146',
 'RE1447M',
 'RE2659R',
 'RE2675C',
 'RE3237C',
 'RE3245C',
 'RE3347C',
 'FAOXC5C5OHm',
 'ADNK3',
 '10FTHF6GLUtl',
 '10FTHFtl',
 '4ABUTtm',
 '4MOPt2im',
 'ACALDt',
 'ACGAMtly',
 'ARTFR12',
 'Asn_X_Ser_Thrtr',
 'BHBt',
 'BHBtm',
 'BILGLCURtr',
 'BILIRUBtr',
 'C226CRNt',
 'CO2t',
 'CO2ter',
 'CRVNCtr',
 'DATPtn',
 'DCTPtn',
 'DGTPtn',
 'DOLGLCP_Lter',
 'DOLMANP_Lter',
 'DOLP_Uter',
 'DTTPtn',
 'FADH2tru',
 'FADtru',
 'FORtr',
 'GALtly',
 'GDPtg',
 'GLCter',
 'GLUt7l',
 'GLXtm',
 'GMPtg',
 'H2O2t',
 'H2O2tm',
 'H2Oter',
 'H2Otg',
 'H2Otly',
 'HMGCOAtm',
 'Htg',
 'Htr',
 'M4MPDOL_Uter',
 'M7MASNBterg',
 'M8MASNterg',
 'MANter',
 'MANtg',
 'MANtly',
 'NADHtru',
 'NADPHtru',
 'NADPtru',
 'NADtru',
 'O2St',
 'O2Stm',
 'O2t',
 'O2ter',
 'O2tm',
 'PCHOL_HSter',
 'PE_HSter',
 'PEt',
 'PGLYCt',
 'PItg',
 'PPItr',
 'PSt3',
 'RETNGLCt2',
 'RETNGLCt2r',
 'RETNt',
 'RETNtr',
 'RETNtr2',
 'S2L2FN2M2MASNt',
 'S2L2N2M2MASNtly',
 'SPH1Pte',
 'UDPGLCter',
 'r0818',
 'r0819',
 'r0838',
 'r0892',
 'r0911',
 'r0940',
 'r1088',
 'r1116',
 'r1143',
 'r1144',
 'r1464',
 'r2444',
 'BCRNe',
 'C4CRNe',
 'HIVCRNe',
 'SBTle',
 'CHSTEROLtrc',
 'FRDPtcr',
 'GLYCTDle',
 'KHte',
 'PPItm',
 'RTOTALFATPc',
 '4HPRO_LTte',
 'AHCYSte',
 'xmpt',
 'dcmpt',
 'HC00342te',
 'EX_13_cis_retnglc_LPAREN_e_RPAREN_',
 'EX_4abut_LPAREN_e_RPAREN_',
 'EX_acac_LPAREN_e_RPAREN_',
 'EX_acald_LPAREN_e_RPAREN_',
 'EX_ach_LPAREN_e_RPAREN_',
 'EX_adn_LPAREN_e_RPAREN_',
 'EX_akg_LPAREN_e_RPAREN_',
 'EX_ala_L_LPAREN_e_RPAREN_',
 'EX_arg_L_LPAREN_e_RPAREN_',
 'EX_asn_L_LPAREN_e_RPAREN_',
 'EX_asp_L_LPAREN_e_RPAREN_',
 'EX_atp_LPAREN_e_RPAREN_',
 'EX_bhb_LPAREN_e_RPAREN_',
 'EX_bilglcur_LPAREN_e_RPAREN_',
 'EX_bilirub_LPAREN_e_RPAREN_',
 'EX_chol_LPAREN_e_RPAREN_',
 'EX_cit_LPAREN_e_RPAREN_',
 'EX_crn_LPAREN_e_RPAREN_',
 'EX_crvnc_LPAREN_e_RPAREN_',
 'EX_cys_L_LPAREN_e_RPAREN_',
 'EX_cytd_LPAREN_e_RPAREN_',
 'EX_dgsn_LPAREN_e_RPAREN_',
 'EX_fuc_L_LPAREN_e_RPAREN_',
 'EX_glc_LPAREN_e_RPAREN_',
 'EX_gln_L_LPAREN_e_RPAREN_',
 'EX_glu_L_LPAREN_e_RPAREN_',
 'EX_gly_LPAREN_e_RPAREN_',
 'EX_glyc_LPAREN_e_RPAREN_',
 'EX_gsn_LPAREN_e_RPAREN_',
 'EX_h_LPAREN_e_RPAREN_',
 'EX_h2o_LPAREN_e_RPAREN_',
 'EX_h2o2_LPAREN_e_RPAREN_',
 'EX_hdca_LPAREN_e_RPAREN_',
 'EX_his_L_LPAREN_e_RPAREN_',
 'EX_ile_L_LPAREN_e_RPAREN_',
 'EX_inost_LPAREN_e_RPAREN_',
 'EX_lac_L_LPAREN_e_RPAREN_',
 'EX_leu_L_LPAREN_e_RPAREN_',
 'EX_lys_L_LPAREN_e_RPAREN_',
 'EX_malt_LPAREN_e_RPAREN_',
 'EX_met_L_LPAREN_e_RPAREN_',
 'EX_nh4_LPAREN_e_RPAREN_',
 'EX_o2_LPAREN_e_RPAREN_',
 'EX_o2s_LPAREN_e_RPAREN_',
 'EX_ocdcea_LPAREN_e_RPAREN_',
 'EX_oxa_LPAREN_e_RPAREN_',
 'EX_pe_hs_LPAREN_e_RPAREN_',
 'EX_pglyc_hs_LPAREN_e_RPAREN_',
 'EX_phe_L_LPAREN_e_RPAREN_',
 'EX_pi_LPAREN_e_RPAREN_',
 'EX_pro_L_LPAREN_e_RPAREN_',
 'EX_ps_hs_LPAREN_e_RPAREN_',
 'EX_retn_LPAREN_e_RPAREN_',
 'EX_Rtotal_LPAREN_e_RPAREN_',
 'EX_ser_L_LPAREN_e_RPAREN_',
 'EX_sph1p_LPAREN_e_RPAREN_',
 'EX_succ_LPAREN_e_RPAREN_',
 'EX_thr_L_LPAREN_e_RPAREN_',
 'EX_thymd_LPAREN_e_RPAREN_',
 'EX_trp_L_LPAREN_e_RPAREN_',
 'EX_tyr_L_LPAREN_e_RPAREN_',
 'EX_uri_LPAREN_e_RPAREN_',
 'EX_utp_LPAREN_e_RPAREN_',
 'EX_vacc_LPAREN_e_RPAREN_',
 'EX_val_L_LPAREN_e_RPAREN_',
 'EX_ahdt_LPAREN_e_RPAREN_',
 'EX_HC00250_LPAREN_e_RPAREN_',
 'EX_HC01361_LPAREN_e_RPAREN_',
 'EX_HC01609_LPAREN_e_RPAREN_',
 'EX_HC01610_LPAREN_e_RPAREN_',
 'EX_ddca_LPAREN_e_RPAREN_',
 'EX_3bcrn_',
 'EX_3ivcrn_',
 'EX_c4crn_',
 'EX_4hpro_LPAREN_e_RPAREN_',
 'EX_sbt_DASH_d_LPAREN_e_RPAREN_',
 'EX_ahcys_LPAREN_e_RPAREN_',
 'EX_xmp_LPAREN_e_RPAREN_',
 'EX_dcmp_LPAREN_e_RPAREN_',
 'EX_HC00342_LPAREN_e_RPAREN_',
 'PMTFATPtc',
 'PROB0AT2tc',
 '2HATVLAChc',
 '2HATVLACtep',
 '4HATVLAChc',
 'ATVLAChc',
 'LVACLAChep',
 'SMVLAChep',
 'TMDtd',
 'adptl',
 'adptn',
 'adptr',
 'adptx',
 'ahcystn',
 'ala_Ltl',
 'ala_Ltm',
 'ala_Ltn',
 'ala_Ltr',
 'ala_Ltx',
 'amettn',
 'amptn',
 'arg_Ltl',
 'arg_Ltn',
 'arg_Ltr',
 'arg_Ltx',
 'asn_Ltl',
 'asn_Ltm',
 'asn_Ltn',
 'asn_Ltr',
 'asn_Ltx',
 'asp_Ltl',
 'asp_Ltm',
 'asp_Ltn',
 'asp_Ltr',
 'asp_Ltx',
 'atptl',
 'atptn',
 'atptr',
 'atptx',
 'cdptn',
 'cmptn',
 'ctptn',
 'cys_Ltl',
 'cys_Ltm',
 'cys_Ltn',
 'cys_Ltr',
 'cys_Ltx',
 'gdptn',
 'gln_Ltl',
 'gln_Ltm',
 'gln_Ltn',
 'gln_Ltr',
 'gln_Ltx',
 'glu_Ltn',
 'glu_Ltr',
 'glu_Ltx',
 'glytl',
 'glytm',
 'glytn',
 'glytr',
 'glytx',
 'gmptn',
 'SK_gpi_hs_r',
 'gtptn',
 'h2o2tl',
 'h2o2tr',
 'h2otn',
 'h2otx',
 'htn',
 'htx',
 'hdcatl',
 'hdcatr',
 'his_Ltl',
 'his_Ltn',
 'his_Ltr',
 'his_Ltx',
 'ile_Ltl',
 'ile_Ltm',
 'ile_Ltn',
 'ile_Ltr',
 'ile_Ltx',
 'leu_Ltl',
 'leu_Ltm',
 'leu_Ltn',
 'leu_Ltr',
 'leu_Ltx',
 'lys_Ltl',
 'lys_Ltn',
 'lys_Ltr',
 'lys_Ltx',
 'met_Ltl',
 'met_Ltm',
 'met_Ltn',
 'met_Ltr',
 'met_Ltx',
 'o2tl',
 'phe_Ltl',
 'phe_Ltm',
 'phe_Ltn',
 'phe_Ltr',
 'phe_Ltx',
 'pitl',
 'pitn',
 'pitx',
 'ppitn',
 'pro_Ltl',
 'pro_Ltn',
 'pro_Ltr',
 'pro_Ltx',
 'ser_Ltl',
 'ser_Ltm',
 'ser_Ltn',
 'ser_Ltr',
 'ser_Ltx',
 'thr_Ltl',
 'thr_Ltm',
 'thr_Ltn',
 'thr_Ltr',
 'thr_Ltx',
 'trp_Ltl',
 'trp_Ltm',
 'trp_Ltn',
 'trp_Ltr',
 'trp_Ltx',
 'tyr_Ltl',
 'tyr_Ltm',
 'tyr_Ltn',
 'tyr_Ltr',
 'tyr_Ltx',
 'uacgamtr',
 'udptl',
 'SK_udpacgal_g',
 'udpacgaltl',
 'udpacgaltr',
 'udpgaltr',
 'umptn',
 'utptn',
 'val_Ltl',
 'val_Ltm',
 'val_Ltn',
 'val_Ltr',
 'val_Ltx']

In [154]:
self.m_model.reactions.get_by_id('BCRNe')

In [130]:
self = res['no_dummy']['model']

In [131]:
self.m_model = params.human_model.copy()

In [133]:
self.m_model

In [129]:
bad_rxn

[]

In [81]:
params.human_model.reactions.get_by_id('ala_Ltl')

In [83]:
res['no_dummy']['sln'][res['no_dummy']['model'].reactions.index('ala_Ltl')]

6.658933832917105e-23

In [84]:
res['dummy_0.879584658137385']['sln'][res['dummy_0.879584658137385']['model'].reactions.index('ala_Ltl_F')]

0.0

In [91]:
test = res['dummy_0.879584658137385']['model'].reactions.get_by_id('ala_Ltl_F')

In [92]:
test.coupled_metabolites

{<Complex FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m at 0x7f4eb81e6c18>: 'catalysis'}

In [95]:
test = res['dummy_0.879584658137385']['model'].reactions.get_by_id('glytl_F')

In [98]:
res['dummy_0.879584658137385']['model'].metabolites.get_by_id('FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m')

In [99]:
res['dummy_0.879584658137385']['model'].metabolites.get_by_id('HGNC:DUMMY_folded_protein_c')

{<Complex FAOXC10080m_FAOXC120100m_FAOXC140120m_FAOXC143_5Z_8Z_11Zm_FAOXC160140m_FAOXC184_6Z_9Z_12Z_15Zm_FAOXC4020m_FAOXC6040m_FAOXC8060m_FAOXC81_5Zm_8_complex_m at 0x7f4eb81e6c18>}

In [121]:
res.keys()

dict_keys(['no_dummy', 'dummy_0.001', 'dummy_sink_0.001', 'dummy_0.879584658137385', 'dummy_sink_0.879584658137385'])

In [ ]:
test.coupled_metabolites

In [123]:
bad_rxn

['ARTPLM3_F',
 'DDPGAm_F',
 'r0480_F',
 'r0584_F',
 'r0788_F',
 'r0789_F',
 'r1146_F',
 'RE1447M_F',
 'RE2659R_F',
 'RE3237C_F',
 'RE3245C_F',
 'RE3347C_F',
 '10FTHFtl_F',
 '4ABUTtm_F',
 'ACALDt_F',
 'Asn_X_Ser_Thrtr_F',
 'BHBt_F',
 'BHBtm_F',
 'BILGLCURtr_F',
 'BILIRUBtr_F',
 'CO2t_F',
 'CO2ter_F',
 'CRVNCtr_F',
 'DATPtn_F',
 'DCTPtn_F',
 'DGTPtn_F',
 'DTTPtn_F',
 'FORtr_F',
 'GDPtg_F',
 'GLCter_F',
 'GLXtm_F',
 'GMPtg_F',
 'H2O2t_F',
 'H2Oter_F',
 'H2Otg_F',
 'H2Otly_F',
 'HMGCOAtm_F',
 'Htg_F',
 'Htr_F',
 'O2St_F',
 'O2Stm_F',
 'O2t_F',
 'O2ter_F',
 'O2tm_F',
 'PCHOL_HSter_F',
 'PE_HSter_F',
 'PEt_F',
 'PGLYCt_F',
 'PPItr_F',
 'PSt3_F',
 'RETNt_F',
 'SPH1Pte_F',
 'UDPGLCter_F',
 'r0819_F',
 'r0838_F',
 'r0892_F',
 'r0911_F',
 'r0940_F',
 'r1088_F',
 'r1116_F',
 'r1464_F',
 'CHSTEROLtrc_F',
 'FRDPtcr_F',
 'GLYCTDle_F',
 'KHte_F',
 'PPItm_F',
 '4HPRO_LTte_F',
 'AHCYSte_F',
 'xmpt_F',
 'dcmpt_F',
 'HC00342te_F',
 'EX_13_cis_retnglc_LPAREN_e_RPAREN__F',
 'EX_4abut_LPAREN_e_RPAREN__F',
 'EX_acac_LPAREN_e_RPAREN__F',
 'EX_acald_LPAREN_e_RPAREN__F',
 'EX_ach_LPAREN_e_RPAREN__F',
 'EX_adn_LPAREN_e_RPAREN__F',
 'EX_akg_LPAREN_e_RPAREN__F',
 'EX_ala_L_LPAREN_e_RPAREN__F',
 'EX_arg_L_LPAREN_e_RPAREN__F',
 'EX_asn_L_LPAREN_e_RPAREN__F',
 'EX_asp_L_LPAREN_e_RPAREN__F',
 'EX_atp_LPAREN_e_RPAREN__F',
 'EX_bhb_LPAREN_e_RPAREN__F',
 'EX_bilglcur_LPAREN_e_RPAREN__F',
 'EX_bilirub_LPAREN_e_RPAREN__F',
 'EX_chol_LPAREN_e_RPAREN__F',
 'EX_cit_LPAREN_e_RPAREN__F',
 'EX_crn_LPAREN_e_RPAREN__F',
 'EX_crvnc_LPAREN_e_RPAREN__F',
 'EX_cys_L_LPAREN_e_RPAREN__F',
 'EX_cytd_LPAREN_e_RPAREN__F',
 'EX_dgsn_LPAREN_e_RPAREN__F',
 'EX_fuc_L_LPAREN_e_RPAREN__F',
 'EX_glc_LPAREN_e_RPAREN__F',
 'EX_gln_L_LPAREN_e_RPAREN__F',
 'EX_glu_L_LPAREN_e_RPAREN__F',
 'EX_gly_LPAREN_e_RPAREN__F',
 'EX_glyc_LPAREN_e_RPAREN__F',
 'EX_gsn_LPAREN_e_RPAREN__F',
 'EX_h_LPAREN_e_RPAREN__F',
 'EX_h2o_LPAREN_e_RPAREN__F',
 'EX_h2o2_LPAREN_e_RPAREN__F',
 'EX_hdca_LPAREN_e_RPAREN__F',
 'EX_his_L_LPAREN_e_RPAREN__F',
 'EX_ile_L_LPAREN_e_RPAREN__F',
 'EX_inost_LPAREN_e_RPAREN__F',
 'EX_lac_L_LPAREN_e_RPAREN__F',
 'EX_leu_L_LPAREN_e_RPAREN__F',
 'EX_lys_L_LPAREN_e_RPAREN__F',
 'EX_malt_LPAREN_e_RPAREN__F',
 'EX_met_L_LPAREN_e_RPAREN__F',
 'EX_nh4_LPAREN_e_RPAREN__F',
 'EX_o2_LPAREN_e_RPAREN__F',
 'EX_o2s_LPAREN_e_RPAREN__F',
 'EX_ocdcea_LPAREN_e_RPAREN__F',
 'EX_oxa_LPAREN_e_RPAREN__F',
 'EX_pe_hs_LPAREN_e_RPAREN__F',
 'EX_pglyc_hs_LPAREN_e_RPAREN__F',
 'EX_phe_L_LPAREN_e_RPAREN__F',
 'EX_pi_LPAREN_e_RPAREN__F',
 'EX_pro_L_LPAREN_e_RPAREN__F',
 'EX_ps_hs_LPAREN_e_RPAREN__F',
 'EX_retn_LPAREN_e_RPAREN__F',
 'EX_Rtotal_LPAREN_e_RPAREN__F',
 'EX_ser_L_LPAREN_e_RPAREN__F',
 'EX_sph1p_LPAREN_e_RPAREN__F',
 'EX_succ_LPAREN_e_RPAREN__F',
 'EX_thr_L_LPAREN_e_RPAREN__F',
 'EX_thymd_LPAREN_e_RPAREN__F',
 'EX_trp_L_LPAREN_e_RPAREN__F',
 'EX_tyr_L_LPAREN_e_RPAREN__F',
 'EX_uri_LPAREN_e_RPAREN__F',
 'EX_utp_LPAREN_e_RPAREN__F',
 'EX_vacc_LPAREN_e_RPAREN__F',
 'EX_val_L_LPAREN_e_RPAREN__F',
 'EX_ahdt_LPAREN_e_RPAREN__F',
 'EX_HC00250_LPAREN_e_RPAREN__F',
 'EX_HC01361_LPAREN_e_RPAREN__F',
 'EX_HC01609_LPAREN_e_RPAREN__F',
 'EX_HC01610_LPAREN_e_RPAREN__F',
 'EX_ddca_LPAREN_e_RPAREN__F',
 'EX_3bcrn__F',
 'EX_3ivcrn__F',
 'EX_c4crn__F',
 'EX_4hpro_LPAREN_e_RPAREN__F',
 'EX_sbt_DASH_d_LPAREN_e_RPAREN__F',
 'EX_ahcys_LPAREN_e_RPAREN__F',
 'EX_xmp_LPAREN_e_RPAREN__F',
 'EX_dcmp_LPAREN_e_RPAREN__F',
 'EX_HC00342_LPAREN_e_RPAREN__F',
 'PROB0AT2tc_F',
 '2HATVLACtep_F',
 'TMDtd_F',
 'adptl_F',
 'adptn_F',
 'adptr_F',
 'adptx_F',
 'ahcystn_F',
 'ala_Ltl_F',
 'ala_Ltm_F',
 'ala_Ltn_F',
 'ala_Ltr_F',
 'ala_Ltx_F',
 'amettn_F',
 'amptn_F',
 'arg_Ltl_F',
 'arg_Ltn_F',
 'arg_Ltr_F',
 'arg_Ltx_F',
 'asn_Ltl_F',
 'asn_Ltm_F',
 'asn_Ltn_F',
 'asn_Ltr_F',
 'asn_Ltx_F',
 'asp_Ltl_F',
 'asp_Ltm_F',
 'asp_Ltn_F',
 'asp_Ltr_F',
 'asp_Ltx_F',
 'atptl_F',
 'atptn_F',
 'atptr_F',
 'atptx_F',
 'cdptn_F',
 'cmptn_F',
 'ctptn_F',
 'cys_Ltl_F',
 'cys_Ltm_F',
 'cys_Ltn_F',
 'cys_Ltr_F',
 'cys_Ltx_F',
 'gdptn_F',
 'gln_Ltl_F',
 'gln_Ltm_F',
 'gln_Ltn_F',
 'gln_Ltr_F',
 'gln_Ltx_F',
 'glu_Ltn_F',
 'glu_Ltr_F',
 'glu_Ltx_F',
 'glytl_F',
 'glytm_F',
 'glytn_F',
 'glytr_F',
 'glytx_F',
 'gmptn_F',
 'SK_gpi_hs_r_F',
 'gtptn_F',
 'h2o2tl_F',
 'h2o2tr_F',
 'h2otn_F',
 'h2otx_F',
 'htn_F',
 'htx_F',
 'hdcatl_F',
 'hdcatr_F',
 'his_Ltl_F',
 'his_Ltn_F',
 'his_Ltr_F',
 'his_Ltx_F',
 'ile_Ltl_F',
 'ile_Ltm_F',
 'ile_Ltn_F',
 'ile_Ltr_F',
 'ile_Ltx_F',
 'leu_Ltl_F',
 'leu_Ltm_F',
 'leu_Ltn_F',
 'leu_Ltr_F',
 'leu_Ltx_F',
 'lys_Ltl_F',
 'lys_Ltn_F',
 'lys_Ltr_F',
 'lys_Ltx_F',
 'met_Ltl_F',
 'met_Ltm_F',
 'met_Ltn_F',
 'met_Ltr_F',
 'met_Ltx_F',
 'o2tl_F',
 'phe_Ltl_F',
 'phe_Ltm_F',
 'phe_Ltn_F',
 'phe_Ltr_F',
 'phe_Ltx_F',
 'pitl_F',
 'pitn_F',
 'pitx_F',
 'ppitn_F',
 'pro_Ltl_F',
 'pro_Ltn_F',
 'pro_Ltr_F',
 'pro_Ltx_F',
 'ser_Ltl_F',
 'ser_Ltm_F',
 'ser_Ltn_F',
 'ser_Ltr_F',
 'ser_Ltx_F',
 'thr_Ltl_F',
 'thr_Ltm_F',
 'thr_Ltn_F',
 'thr_Ltr_F',
 'thr_Ltx_F',
 'trp_Ltl_F',
 'trp_Ltm_F',
 'trp_Ltn_F',
 'trp_Ltr_F',
 'trp_Ltx_F',
 'tyr_Ltl_F',
 'tyr_Ltm_F',
 'tyr_Ltn_F',
 'tyr_Ltr_F',
 'tyr_Ltx_F',
 'uacgamtr_F',
 'udptl_F',
 'SK_udpacgal_g_F',
 'udpacgaltl_F',
 'udpacgaltr_F',
 'udpgaltr_F',
 'umptn_F',
 'utptn_F',
 'val_Ltl_F',
 'val_Ltm_F',
 'val_Ltn_F',
 'val_Ltr_F',
 'val_Ltx_F']

In [90]:
params.human_model.reactions.get_by_id('ala_Ltl')

In [75]:
fail

,no_dummy,dummy_0.001,dummy_sink_0.001,dummy_0.879584658137385,dummy_sink_0.879584658137385
protein_biomass_to_biomass,4.51572e-10,8.16609e-10,4.50324e-10,3.6358e-12,4.07357e-12
rRNA_biomass_to_biomass,2.73894e-14,4.6579e-15,3.70095e-14,1.69961e-15,2.77796e-14
mRNA_biomass_to_biomass,3.66401e-10,5.69116e-13,3.67188e-10,3.05946e-13,7.84143e-10
premRNA_biomass_to_biomass,1.86696e-22,0,0,7.87498e-10,0
other_rna_biomass_to_biomass,-7.10693e-23,0,1.33385e-22,2.59927e-16,1.00275e-17
ala_Ltl_R,NaN,0,0,-2.18494e-19,1.2228e-20
glytl_R,NaN,0,0,-3.13813e-19,-1.37275e-35
HGNC:10416_folded_protein_c_POLYUBIQUITINATIONc,0,2.02679e-52,0,-7.3096e-19,0
HGNC:10416_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-7.3096e-19,0
HGNC:18476_folded_protein_c_POLYUBIQUITINATIONc,0,-1.52009e-51,0,-7.3096e-19,-2.02679e-52
HGNC:18476_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-7.3096e-19,0
HGNC:10418_folded_protein_c_POLYUBIQUITINATIONc,-2.02679e-52,-1.0134e-52,0,-7.3096e-19,-4.05359e-52
HGNC:10418_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-7.3096e-19,0
HGNC:10419_folded_protein_c_POLYUBIQUITINATIONc,-3.71436e-42,-3.04019e-52,4.27648e-10,-7.3096e-19,1.89957e-10
HGNC:10419_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,4.27648e-10,-7.3096e-19,1.89957e-10
HGNC:10348_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-7.3096e-19,0
HGNC:10349_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-7.3096e-19,0
HGNC:10350_folded_protein_c_POLYUBIQUITINATIONc,0,0,0,-7.3096e-19,0
HGNC:10350_folded_protein_c_PROTEASOMAL_DEGRADATIONc,4.69195e-42,0,0,-7.3096e-19,0
HGNC:17094_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-7.3096e-19,0
HGNC:12458_processed_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-7.3096e-19,0
HGNC:21108_unfolded_protein_c_PROTEASOMAL_DEGRADATIONc,0,0,0,-2.79543e-19,0
HGNC:28369_folded_protein_c_POLYUBIQUITINATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:28369_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:29874_folded_protein_c_POLYUBIQUITINATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:29874_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:17821_folded_protein_n_PROTEASOMAL_DEGRADATIONn,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:15913_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:19072_folded_protein_c_POLYUBIQUITINATIONc,0,-3.64441e-22,-1.20541e-19,-1.28629e-22,-1.58439e-19
HGNC:19072_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:29093_folded_protein_n_PROTEASOMAL_DEGRADATIONn,0,0,0,0,-1.58439e-19
HGNC:3447_folded_protein_n_PROTEASOMAL_DEGRADATIONn,0,0,0,0,-1.58439e-19
HGNC:24432_folded_protein_c_POLYUBIQUITINATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:24432_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64404e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:24971_folded_protein_c_POLYUBIQUITINATIONc,0,-3.64568e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:24971_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64441e-22,-1.20541e-19,-1.31182e-22,-1.58439e-19
HGNC:24511_folded_protein_c_POLYUBIQUITINATIONc,0,-3.64441e-22,-1.20541e-19,-1.31538e-22,-1.58439e-19
HGNC:24511_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64441e-22,-1.20541e-19,-1.31538e-22,-1.58439e-19
HGNC:19071_folded_protein_c_POLYUBIQUITINATIONc,0,-3.64441e-22,-1.20541e-19,-1.29855e-22,-1.58439e-19
HGNC:19071_folded_protein_c_PROTEASOMAL_DEGRADATIONc,0,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19
HGNC:25407_folded_protein_c_POLYUBIQUITINATIONc,-1.21169e-19,-3.64441e-22,-1.20541e-19,-1.30211e-22,-1.58439e-19
HGNC:25407_folded_protein_c_PROTEASOMAL_DEGRADATIONc,-1.21169e-19,-3.64441e-22,-1.20541e-19,-1.311e-22,-1.58439e-19

In [65]:
r_ids

['HGNC:17821_folded_protein_n_PROTEASOMAL_DEGRADATIONn',
 'ala_Ltl_R',
 'HGNC:24432_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'mRNA_biomass_to_biomass',
 'HGNC:29093_folded_protein_n_PROTEASOMAL_DEGRADATIONn',
 'HGNC:10418_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:19071_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:25407_folded_protein_c_POLYUBIQUITINATIONc',
 'other_rna_biomass_to_biomass',
 'HGNC:9198_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:29874_folded_protein_c_POLYUBIQUITINATIONc',
 'glytl_R',
 'HGNC:3447_folded_protein_n_PROTEASOMAL_DEGRADATIONn',
 'HGNC:10348_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'DNA_biomass_to_biomass',
 'HGNC:17094_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'rRNA_biomass_to_biomass',
 'premRNA_biomass_to_biomass',
 'HGNC:24511_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:28369_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:24511_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:24971_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'lipid_biomass_to_biomass',
 'HGNC:28369_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'carbohydrate_biomass_formation',
 'HGNC:10416_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:24432_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:29874_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:9198_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:24971_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:10419_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'lipid_biomass_formation',
 'HGNC:10354_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:12458_processed_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'protein_biomass_to_biomass',
 'HGNC:15913_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:10419_folded_protein_c_POLYUBIQUITINATIONc',
 'carbohydrate_biomass_to_biomass',
 'HGNC:19072_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:10350_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:10350_folded_protein_c_POLYUBIQUITINATIONc',
 'biomass_dilution',
 'HGNC:18476_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:10349_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:18476_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:10354_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:21108_unfolded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:10416_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:19072_folded_protein_c_POLYUBIQUITINATIONc',
 'HGNC:19071_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:25407_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'DNA_biomass_formation',
 'HGNC:10418_folded_protein_c_PROTEASOMAL_DEGRADATIONc',
 'HGNC:10420_TRANSCRIPTION_ELONGATION',
 'tRNA_biomass_to_biomass']

In [52]:
r

,no_dummy,dummy_0.001,dummy_sink_0.001,dummy_0.879584658137385,dummy_sink_0.879584658137385
HGNC:10420_TRANSCRIPTION_ELONGATION,NaN,NaN,NaN,NaN,3.00673e-22
HGNC:10354_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,1.91646e-46
HGNC:10354_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:9198_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-2.02679e-52
HGNC:9198_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
ala_Ltl_R,NaN,NaN,NaN,NaN,1.2228e-20
glytl_R,NaN,NaN,NaN,NaN,-1.37275e-35
HGNC:10416_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,0
HGNC:10416_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:18476_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-2.02679e-52
HGNC:18476_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:10418_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-4.05359e-52
HGNC:10418_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:10419_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,1.89957e-10
HGNC:10419_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,1.89957e-10
HGNC:10348_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:10349_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:10350_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,0
HGNC:10350_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:17094_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:12458_processed_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:21108_unfolded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,0
HGNC:28369_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:28369_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:29874_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:29874_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:17821_folded_protein_n_PROTEASOMAL_DEGRADATIONn,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:15913_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:19072_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:19072_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:29093_folded_protein_n_PROTEASOMAL_DEGRADATIONn,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:3447_folded_protein_n_PROTEASOMAL_DEGRADATIONn,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:24432_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:24432_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:24971_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:24971_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:24511_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:24511_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:19071_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:19071_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:25407_folded_protein_c_POLYUBIQUITINATIONc,NaN,NaN,NaN,NaN,-1.58439e-19
HGNC:25407_folded_protein_c_PROTEASOMAL_DEGRADATIONc,NaN,NaN,NaN,NaN,-1.58439e-19

In [43]:
res['dummy_sink_0.879584658137385']['model'].reactions.get_by_id('protein_biomass_to_biomass')

In [44]:
res['dummy_sink_0.001']['model'].reactions.get_by_id('protein_biomass_to_biomass')

In [40]:
biomass.pb_reaction

In [ ]:
# tol = max([abs(i) for i in res['no_dummy']['infeasible_reactions'].values()])
# print('Tolerance: {}'.format(tol))
# fail = {k:v for k,v in res['dummy']['infeasible_reactions'].items() if abs(v) >= tol}

# fail_ids = set(pd.Series(list(fail.keys())).apply(lambda x: x.split('_')[0]))
# fail_metabs = [m for m in res['dummy']['model'].metabolites if m.id.split('_')[0] in fail_ids]